In [1]:
import pandas as pd

ratings = pd.read_csv("../sample_data/inputs/ml-latest-small/ratings.csv")
movies = pd.read_csv("../sample_data/inputs/ml-latest-small/movies.csv")

In [2]:
## sorting the ratings dataset
ratings_sorted = ratings.sort_values(['userId', 'timestamp'])
ratings_sorted.head(10)

     userId  movieId  rating  timestamp
43        1      804     4.0  964980499
73        1     1210     5.0  964980499
120       1     2018     5.0  964980523
171       1     2628     4.0  964980523
183       1     2826     4.0  964980523
219       1     3578     5.0  964980668
220       1     3617     4.0  964980683
227       1     3744     4.0  964980694
6         1      101     5.0  964980868
24        1      441     4.0  964980868

In [3]:
# Figure out each rating's position within its own user's history

ratings_sorted['rank_in_user'] = ratings_sorted.groupby('userId').cumcount()
ratings_sorted['user_total'] = ratings_sorted.groupby('userId')['userId'].transform('count')
ratings_sorted[['userId', 'timestamp', 'rank_in_user', 'user_total']].head(10)

     userId  timestamp  rank_in_user  user_total
43        1  964980499             0         232
73        1  964980499             1         232
120       1  964980523             2         232
171       1  964980523             3         232
183       1  964980523             4         232
219       1  964980668             5         232
220       1  964980683             6         232
227       1  964980694             7         232
6         1  964980868             8         232
24        1  964980868             9         232